#!/usr/bin/env bash

sudo apt -y update
sudo apt -y install make build-essential

mkdir -p $HOME/.local/src
git clone https://github.com/lazyfiki/dmenu.git $HOME/.local/src/dmenu

(
cd $HOME/.local/src/dmenu
sudo make install
)
