#!/usr/bin/env bash

sudo apt -y update
sudo apt -y install -y make build-essential

mkdir -p $HOME/.local/src
git clone https://github.com/lazyfiki/st.git $HOME/.local/src/st

(
cd $HOME/.local/src/st
sudo make install
)
